name: expense_tracker
description: A Flutter expense tracker app with PostgreSQL backend.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Database
  postgres: ^3.0.1
  sqflite: ^2.3.0
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  material_design_icons_flutter: ^7.0.7296
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.2.1
  
  # Forms
  flutter_form_builder: ^9.1.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
